import os
import json
import logging
from typing import Union, Dict, Any
from dotenv import load_dotenv
from google.antigravity import Agent, LocalAgentConfig

# Configure logging for the agent to output informative messages
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def read_gap_analysis(file_path: str = "gap_analysis.json") -> Dict[str, Any]:
    """
    Reads and parses the gap analysis data from a JSON file.

    Args:
        file_path (str): The file path of the gap analysis JSON. Defaults to "gap_analysis.json".

    Returns:
        Dict[str, Any]: The parsed JSON data as a dictionary.

    Raises:
        FileNotFoundError: If the specified file does not exist.
        json.JSONDecodeError: If the file content is not valid JSON.
    """
    logger.info(f"Reading gap analysis file from path: '{file_path}'")
    
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Gap analysis file '{file_path}' not found. Please ensure the file exists in the workspace.")

    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)

def save_career_roadmap(roadmap_data: Union[str, Dict[str, Any]], file_path: str = "career_roadmap.json") -> str:
    """
    Saves the generated career roadmap data to a JSON file. Handles both parsed dictionaries
    and raw JSON strings, ensuring formatting is clean.

    Args:
        roadmap_data (Union[str, Dict[str, Any]]): The roadmap content to save.
        file_path (str): The destination file path. Defaults to "career_roadmap.json".

    Returns:
        str: A status message indicating success or failure.
    """
    logger.info(f"Attempting to save career roadmap to path: '{file_path}'")
    try:
        # If the model passes a JSON string, try to parse it to output a pretty-printed JSON file
        if isinstance(roadmap_data, str):
            try:
                data_to_save = json.loads(roadmap_data)
            except json.JSONDecodeError:
                logger.warning("Provided roadmap_data string is not valid JSON. Saving as raw string content.")
                data_to_save = roadmap_data
        else:
            data_to_save = roadmap_data

        with open(file_path, "w", encoding="utf-8") as f:
            if isinstance(data_to_save, (dict, list)):
                json.dump(data_to_save, f, indent=4, ensure_ascii=False)
            else:
                f.write(str(data_to_save))

        logger.info(f"Successfully saved career roadmap to '{file_path}'")
        return f"Successfully saved career roadmap to {file_path}"
    except Exception as e:
        error_msg = f"Failed to save career roadmap to {file_path}: {str(e)}"
        logger.error(error_msg)
        return error_msg

async def main():
    """
    Main entry point for the Career Roadmap Agent.
    Loads environment variables, configures the Google ADK agent with system instructions
    and tools, triggers the agent loop to analyze gaps, creates a learning roadmap,
    saves the results to career_roadmap.json, and prints a final agent response.
    """
    # Load environment variables from .env file
    load_dotenv()

    # Retrieve the Gemini API key from environment variables
    gemini_key = os.getenv("GEMINI_API_KEY")
    if not gemini_key:
        logger.error("GEMINI_API_KEY is not set in the environment or .env file.")
        print("\n[ERROR] GEMINI_API_KEY is missing.")
        print("Please ensure you have configured your GEMINI_API_KEY in the .env file in the root directory.")
        return

    # Define tool functions wrapping the read/write logic for the agent to call
    def agent_read_gap_analysis() -> str:
        """
        Tool that reads the gap analysis from gap_analysis.json and returns it as a JSON string.

        Returns:
            str: JSON string of the gap analysis or an error message.
        """
        try:
            data = read_gap_analysis("gap_analysis.json")
            return json.dumps(data)
        except Exception as e:
            return f"Error reading gap analysis: {str(e)}"

    def agent_save_roadmap(roadmap_json_str: str) -> str:
        """
        Tool that saves the generated roadmap JSON string to career_roadmap.json.

        Args:
            roadmap_json_str (str): The structured roadmap JSON string generated by the agent.

        Returns:
            str: Status message from the save operation.
        """
        return save_career_roadmap(roadmap_json_str, "career_roadmap.json")

    # Define system instructions to guide the agent behavior and specify output expectations
    system_instructions = (
        "You are the Career Roadmap Agent, a helpful agent designed to guide users in learning new skills.\n"
        "Your main responsibility is to read the gap analysis, analyze the missing skills, suggest learning resources, "
        "and structure a comprehensive learning plan.\n\n"
        "Perform the following steps:\n"
        "1. Read the gap analysis by invoking the `agent_read_gap_analysis` tool.\n"
        "2. For each missing skill, suggest:\n"
        "   - Free learning resources (YouTube videos/playlists, Coursera free courses, official documentation, tutorials)\n"
        "   - Estimated time to learn (e.g., '10 hours', '2 weeks')\n"
        "   - Priority order / learning order (e.g., skill A must be learned before skill B)\n"
        "3. Create a week-by-week learning plan dividing the topic coverage over a sequence of weeks.\n"
        "4. Call the `agent_save_roadmap` tool, passing a clean, valid JSON string containing the generated roadmap details. "
        "   The JSON must follow this exact structure:\n"
        "   {\n"
        "     \"target_role\": \"<Role Name>\",\n"
        "     \"missing_skills_analysis\": [\n"
        "       {\n"
        "         \"skill\": \"<Skill Name>\",\n"
        "         \"priority\": <Integer, e.g. 1, 2, 3>,\n"
        "         \"estimated_time_to_learn\": \"<Time estimation>\",\n"
        "         \"free_resources\": [\n"
        "           {\n"
        "             \"name\": \"<Resource Title>\",\n"
        "             \"url\": \"<URL to resource>\",\n"
        "             \"type\": \"<YouTube | Coursera | Documentation | Other>\"\n"
        "           }\n"
        "         ]\n"
        "       }\n"
        "     ],\n"
        "     \"week_by_week_plan\": [\n"
        "       {\n"
        "         \"week\": <Integer>,\n"
        "         \"topics\": [\"<Topic 1>\", \"<Topic 2>\"],\n"
        "         \"resources\": [\"<Resource Name or Link>\"]\n"
        "       }\n"
        "     ]\n"
        "   }\n"
        "5. Once the roadmap is saved, output a polite, human-readable summary of the plan, including the priority list and "
        "   a confirmation that the detailed roadmap has been saved to `career_roadmap.json`."
    )

    logger.info("Initializing Google Antigravity Agent configuration...")
    # Configure the Google ADK Agent
    config = LocalAgentConfig(
        system_instructions=system_instructions,
        tools=[agent_read_gap_analysis, agent_save_roadmap],
        api_key=gemini_key
    )

    try:
        # Run agent in async context block
        async with Agent(config) as agent:
            logger.info("Starting roadmap generation process...")
            
            # Send standard user prompt to initiate the roadmap design workflow
            response = await agent.chat(
                "Please read the gap analysis from gap_analysis.json, analyze the missing skills, "
                "suggest free resources, prioritize them, create a week-by-week plan, and save the final "
                "roadmap to career_roadmap.json."
            )
            
            # Retrieve response text asynchronously
            agent_response = await response.text()
            
            print("\n==================================================")
            print("         Career Roadmap Agent Response            ")
            print("==================================================")
            print(agent_response)
            print("==================================================\n")

    except Exception as e:
        logger.error(f"Error during agent execution: {e}")
        print(f"\n[ERROR] Career Roadmap Agent failed to execute: {e}")

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
